/*
 * Automatically generated file. DO NOT EDIT.
 * Espressif IoT Development Framework (ESP-IDF) Configuration Header
 */
#ifndef __ESP_SDKCONFIG_H__
#define __ESP_SDKCONFIG_H__

/* ESP32-S3 Target */
#define CONFIG_IDF_TARGET_ESP32S3 1
#define CONFIG_IDF_TARGET "esp32s3"
#define CONFIG_IDF_TARGET_ARCH_XTENSA 1

/* PSRAM Configuration */
#define CONFIG_SPIRAM 1
#define CONFIG_SPIRAM_MODE_OCT 1
#define CONFIG_SPIRAM_SPEED_80M 1
#define CONFIG_SPIRAM_USE_MALLOC 1
#define CONFIG_SPIRAM_SIZE 8388608

/* Flash Configuration */
#define CONFIG_ESPTOOLPY_FLASHMODE_DIO 1
#define CONFIG_ESPTOOLPY_FLASHFREQ_80M 1
#define CONFIG_ESPTOOLPY_FLASHSIZE_4MB 1
#define CONFIG_ESPTOOLPY_FLASHSIZE 0x400000

/* Arduino Configuration */
#define CONFIG_ARDUINO_RUNNING_CORE 1
#define CONFIG_ARDUINO_EVENT_RUNNING_CORE 1
#define ARDUINO_RUNNING_CORE 1
#define ARDUINO_EVENT_RUNNING_CORE 1

/* FreeRTOS Configuration */
#define CONFIG_FREERTOS_HZ 1000
#define CONFIG_FREERTOS_UNICORE 0
#define CONFIG_FREERTOS_MAX_TASK_NAME_LEN 16
#define CONFIG_FREERTOS_THREAD_LOCAL_STORAGE_POINTERS 1
#define CONFIG_FREERTOS_IDLE_TASK_STACKSIZE 1536
#define CONFIG_FREERTOS_ISR_STACKSIZE 1536
#define CONFIG_FREERTOS_TIMER_TASK_PRIORITY 1
#define CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH 2048
#define CONFIG_FREERTOS_TIMER_QUEUE_LENGTH 10
#define CONFIG_FREERTOS_QUEUE_REGISTRY_SIZE 0
#define CONFIG_FREERTOS_USE_TRACE_FACILITY 0
#define CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS 0
#define CONFIG_FREERTOS_CHECK_STACKOVERFLOW_NONE 1

/* WiFi Configuration */
#define CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM 10
#define CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM 32
#define CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER_NUM 32
#define CONFIG_ESP32_WIFI_TX_BUFFER_TYPE 1
#define CONFIG_ESP32_WIFI_STATIC_TX_BUFFER_NUM 0
#define CONFIG_ESP32_WIFI_CACHE_TX_BUFFER_NUM 32
#define CONFIG_ESP32_WIFI_AMPDU_TX_ENABLED 1
#define CONFIG_ESP32_WIFI_AMPDU_RX_ENABLED 1
#define CONFIG_ESP32_WIFI_NVS_ENABLED 1

/* Camera Configuration */
#define CONFIG_CAMERA_CORE0 1
#define CONFIG_CAMERA_DMA_BUFFER_SIZE_MAX 32768

/* Log Configuration */
#define CONFIG_LOG_DEFAULT_LEVEL 3
#define CONFIG_LOG_DEFAULT_LEVEL_INFO 1
#define CONFIG_LOG_MAXIMUM_LEVEL 5
#define CONFIG_LOG_MAXIMUM_LEVEL_VERBOSE 1
#define CONFIG_LOG_COLORS 1

/* Log Levels */
/* Log level macros removed to avoid name collisions with esp-idf headers.
    esp-idf's `esp_log.h` defines an enum with the same names (e.g. ESP_LOG_INFO).
    Defining those here as macros causes preprocessor substitution and breaks
    compilation when `esp_log.h` is included. Use the CONFIG_* values below
    for compile-time local log level defaults. */

/* LOG_LOCAL_LEVEL 매크로 - 로컬 파일의 로그 레벨 설정 (use CONFIG value)
    If a file still needs to override LOG_LOCAL_LEVEL, define it before
    including headers. */
#ifndef LOG_LOCAL_LEVEL
#define LOG_LOCAL_LEVEL CONFIG_LOG_DEFAULT_LEVEL
#endif

/* LWIP Configuration */
#define CONFIG_LWIP_DHCP_COARSE_TIMER_SECS 60
#define CONFIG_LWIP_MAX_SOCKETS 10
#define CONFIG_LWIP_SO_REUSE 1
#define CONFIG_LWIP_SO_RCVBUF 1
#define CONFIG_LWIP_DHCP_MAX_NTP_SERVERS 1
#define CONFIG_LWIP_SNTP_UPDATE_DELAY 3600000
#define CONFIG_TCP_OVERSIZE_MSS 1
#define CONFIG_LWIP_TCP_OVERSIZE_MSS 1

/* USB CDC */
#define CONFIG_USB_CDC_ENABLED 1
#define CONFIG_TINYUSB_CDC_ENABLED 1

/* Brownout Detector */
#define CONFIG_BROWNOUT_DET 1
#define CONFIG_BROWNOUT_DET_LVL_SEL 7
#define CONFIG_BROWNOUT_DET_LVL 7

/* Watchdog Timer */
#define CONFIG_ESP_TASK_WDT 1
#define CONFIG_ESP_TASK_WDT_TIMEOUT_S 5
#define CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU0 1
#define CONFIG_ESP_INT_WDT 1
#define CONFIG_ESP_INT_WDT_TIMEOUT_MS 300

/* Memory Configuration */
#define CONFIG_ESP32S3_INSTRUCTION_CACHE_SIZE 0x4000
#define CONFIG_ESP32S3_DATA_CACHE_SIZE 0x10000
#define CONFIG_ESP32S3_INSTRUCTION_CACHE_LINE_SIZE 32
#define CONFIG_ESP32S3_DATA_CACHE_LINE_SIZE 64

/* Newlib Configuration */
#define CONFIG_NEWLIB_NANO_FORMAT 1
#define CONFIG_NEWLIB_STDOUT_LINE_ENDING_CRLF 1
#define CONFIG_NEWLIB_STDIN_LINE_ENDING_CR 1

/* System */
#define CONFIG_ESP_SYSTEM_EVENT_QUEUE_SIZE 32
#define CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE 2304
#define CONFIG_ESP_MAIN_TASK_STACK_SIZE 3584
#define CONFIG_ESP_MAIN_TASK_AFFINITY_CPU0 1
#define CONFIG_ESP_MINIMAL_SHARED_STACK_SIZE 2048

/* Partition Table */
#define CONFIG_PARTITION_TABLE_CUSTOM 1
#define CONFIG_PARTITION_TABLE_CUSTOM_FILENAME "partitions.csv"
#define CONFIG_PARTITION_TABLE_FILENAME "partitions.csv"

/* SPI Flash */
#define CONFIG_SPI_FLASH_DANGEROUS_WRITE_ABORTS 1
#define CONFIG_SPI_FLASH_YIELD_DURING_ERASE 1
#define CONFIG_SPI_FLASH_ERASE_YIELD_DURATION_MS 20
#define CONFIG_SPI_FLASH_ERASE_YIELD_TICKS 1

/* HAL */
#define CONFIG_HAL_ASSERTION_EQUALS_SYSTEM 1
#define CONFIG_HAL_DEFAULT_ASSERTION_LEVEL 2

#endif /* __ESP_SDKCONFIG_H__ */
